const CONTENT_STRATEGIES = Object.freeze({
  blog_post: {
    format: "educational SEO-style blog post",
    intent: "teach, explain, and build trust before a soft CTA",
    structure: [
      "SEO-friendly title",
      "short introduction that frames the reader's problem",
      "3-5 educational sections with useful explanations",
      "practical examples or implications for the audience",
      "brief conclusion",
      "soft CTA at the end only",
    ],
    avoid: [
      "sales-page language",
      "email-style urgency",
      "repeating sign-up prompts throughout the article",
      "turning the entire article into product promotion",
    ],
    ctaStyle: "soft",
    approximateLength: "700-1000 words unless the user asks for shorter",
    outputShape: {
      type: "blog_post",
      title: "",
      metaDescription: "",
      hook: "",
      introduction: "",
      sections: [{ heading: "", body: "" }],
      conclusion: "",
      cta: "",
      targetAudience: "",
      primaryKeyword: "",
      secondaryKeywords: [""],
      metadata: { wordCount: 0 },
    },
  },
  email: {
    format: "marketing email",
    intent: "drive one focused action from the reader",
    structure: [
      "subject-style title",
      "personal opening",
      "short problem/value explanation",
      "clear benefit bullets or short paragraphs",
      "single direct CTA",
    ],
    avoid: [
      "long article sections",
      "SEO headings",
      "multiple competing CTAs",
    ],
    ctaStyle: "direct",
    approximateLength: "120-220 words",
    outputShape: {
      type: "email",
      subject: "",
      previewText: "",
      body: "",
      cta: "",
      metadata: { wordCount: 0 },
    },
  },
  newsletter: {
    format: "newsletter issue",
    intent: "inform and nurture with a useful editorial rhythm",
    structure: [
      "newsletter subject/title",
      "editorial intro",
      "3-4 update or insight sections",
      "recommended next step",
      "friendly sign-off",
    ],
    avoid: [
      "hard-sell ad copy",
      "landing page sections",
      "overly long paragraphs",
    ],
    ctaStyle: "moderate",
    approximateLength: "300-500 words",
    outputShape: {
      type: "newsletter",
      subject: "",
      introduction: "",
      sections: [{ heading: "", body: "" }],
      closing: "",
      cta: "",
      metadata: { wordCount: 0 },
    },
  },
  landing_page: {
    format: "landing page copy",
    intent: "convert the visitor with clear positioning and proof",
    structure: [
      "hero headline",
      "subheadline",
      "problem section",
      "benefits",
      "how it works",
      "proof or trust section",
      "strong CTA section",
    ],
    avoid: [
      "blog-style educational essay",
      "newsletter sign-off",
      "burying the CTA",
    ],
    ctaStyle: "strong",
    approximateLength: "500-800 words",
    outputShape: {
      type: "landing_page",
      hero: { headline: "", subheadline: "" },
      benefits: [{ title: "", description: "" }],
      features: [{ title: "", description: "" }],
      socialProof: "",
      faqs: [{ question: "", answer: "" }],
      cta: { label: "", supportingText: "" },
      metadata: { wordCount: 0 },
    },
  },
  case_study: {
    format: "case study narrative",
    intent: "show transformation through context, challenge, solution, and results",
    structure: [
      "case study title",
      "background",
      "challenge",
      "solution",
      "results or expected impact",
      "takeaways",
      "CTA",
    ],
    avoid: [
      "unsupported fake metrics",
      "generic testimonial claims",
      "pure ad copy",
    ],
    ctaStyle: "consultative",
    approximateLength: "600-900 words",
    outputShape: {
      type: "case_study",
      title: "",
      background: "",
      challenge: "",
      solution: "",
      results: "",
      takeaways: [""],
      cta: "",
      metadata: { wordCount: 0 },
    },
  },
  linkedin_post: {
    format: "LinkedIn post",
    intent: "spark professional interest and conversation",
    structure: [
      "strong first-line hook",
      "short insight-driven paragraphs",
      "specific point of view",
      "practical takeaway",
      "conversation CTA",
    ],
    avoid: [
      "long blog article",
      "Instagram-style hashtag blocks",
      "salesy landing-page copy",
    ],
    ctaStyle: "conversation",
    approximateLength: "120-220 words",
    outputShape: {
      type: "linkedin_post",
      hook: "",
      body: "",
      takeaway: "",
      cta: "",
      hashtags: [""],
      metadata: { wordCount: 0 },
    },
  },
  instagram_caption: {
    format: "Instagram caption",
    intent: "capture attention quickly and drive lightweight engagement",
    structure: [
      "short hook",
      "simple benefit or story",
      "clear CTA",
      "5-8 relevant hashtags",
    ],
    avoid: [
      "long SEO article",
      "formal corporate language",
      "dense paragraphs",
    ],
    ctaStyle: "engagement",
    approximateLength: "80-160 words",
    outputShape: {
      type: "instagram_caption",
      hook: "",
      caption: "",
      cta: "",
      hashtags: [""],
      metadata: { wordCount: 0 },
    },
  },
});

function buildContentStrategy(brief) {
  const task = brief?.task || "blog_post";
  return CONTENT_STRATEGIES[task] || CONTENT_STRATEGIES.blog_post;
}

module.exports = { buildContentStrategy, CONTENT_STRATEGIES };
