const DEFAULT_WORKFLOW = Object.freeze([
  { module: "research", task: "market", label: "Market Research" },
  { module: "seo", task: "keywords", label: "Keyword Research" },
  { module: "content", task: "blog", label: "Blog Post" },
  { module: "creative", task: "image_post", label: "Image Post" },
  { module: "ads", task: "google_ads", label: "Google Ads" },
]);

const HEALTH_WEIGHTS = Object.freeze({
  workflowCompletion: 0.45,
  approvalReadiness: 0.25,
  assetReadiness: 0.2,
  contextCompleteness: 0.1,
});

const TASK_ALIASES = Object.freeze({
  market: "market_research",
  market_research: "market_research",
  audience: "audience_analysis",
  audience_analysis: "audience_analysis",
  competitor: "competitor_analysis",
  competitor_analysis: "competitor_analysis",
  trends: "trends_research",
  trends_research: "trends_research",
  pain_points: "pain_points_research",
  pain_points_research: "pain_points_research",
  opportunities: "opportunities_research",
  opportunities_research: "opportunities_research",
  keywords: "keyword_research",
  keyword_research: "keyword_research",
  clusters: "keyword_cluster",
  keyword_cluster: "keyword_cluster",
  topics: "topic_cluster",
  topic_cluster: "topic_cluster",
  strategy: "seo_strategy",
  seo_strategy: "seo_strategy",
  meta: "meta_description",
  meta_description: "meta_description",
  faq: "faq_generation",
  faq_generation: "faq_generation",
  blog: "blog_draft",
  blog_post: "blog_draft",
  landing: "blog_draft",
  landing_page: "blog_draft",
  case_study: "blog_draft",
  linkedin: "blog_draft",
  linkedin_post: "blog_draft",
  instagram: "blog_draft",
  instagram_caption: "blog_draft",
  email: "email_draft",
  newsletter: "email_draft",
  image_post: "creative_concept",
  carousel: "creative_concept",
  ad_creative: "creative_concept",
  banner: "creative_concept",
  product_mockup: "creative_concept",
  campaign_package: "creative_concept",
  google_ads: "ad_copy",
  meta_ads: "ad_copy",
  linkedin_ads: "ad_copy",
  tiktok_ads: "ad_copy",
  video_script: "video_script",
  storyboard: "storyboard",
});

module.exports = { DEFAULT_WORKFLOW, HEALTH_WEIGHTS, TASK_ALIASES };
