drop trigger if exists knowledge_audit_is_append_only on public.knowledge_audit_events;
drop trigger if exists knowledge_version_evidence_is_append_only on public.knowledge_version_evidence;
drop trigger if exists knowledge_candidate_evidence_is_append_only on public.knowledge_candidate_evidence;
drop trigger if exists knowledge_normalizations_are_append_only on public.knowledge_normalizations;
drop trigger if exists knowledge_sources_are_immutable on public.knowledge_sources;
drop trigger if exists knowledge_versions_are_append_only on public.business_knowledge_versions;
drop trigger if exists knowledge_versions_enforce_chain on public.business_knowledge_versions;
drop view if exists public.current_business_knowledge_versions;
drop function if exists public.reject_knowledge_audit_mutation();
drop function if exists public.reject_immutable_knowledge_record_mutation();
drop function if exists public.enforce_knowledge_source_immutability();
drop function if exists public.reject_knowledge_version_mutation();
drop function if exists public.enforce_knowledge_version_chain();
drop table if exists public.knowledge_audit_events;
drop table if exists public.knowledge_candidate_updates;
drop table if exists public.knowledge_version_evidence;
drop table if exists public.business_knowledge_versions;
drop table if exists public.knowledge_conflicts;
drop table if exists public.knowledge_candidate_evidence;
drop table if exists public.knowledge_candidates;
drop table if exists public.knowledge_normalizations;
drop table if exists public.knowledge_sources;
drop function if exists public.is_business_creator(uuid);
drop function if exists public.is_business_member(uuid);
drop table if exists public.business_memberships;
drop table if exists public.businesses;
