-- Learning Memory v1.0. Governed observations -> hypotheses -> validation -> human-approved versions.
create table if not exists public.learning_observations (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),source_kind text not null check(source_kind in('campaign_event','analytics_observation','experiment_result','customer_response','sales_feedback','human_note','external_context')),source_reference_id text not null,campaign_id uuid,experiment_id text,metric text not null,value jsonb not null,unit text not null,sample_basis jsonb not null default '{}',scope jsonb not null,observed_at timestamptz not null,collection_window jsonb not null,attribution_method text not null,reliability numeric not null check(reliability between 0 and 1),provenance_hash text not null,metadata jsonb not null default '{}',status text not null default 'observed' check(status in('observed','archived')),created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),unique(business_id,source_kind,source_reference_id,provenance_hash)
);
create table if not exists public.learning_hypotheses (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),identity_key text not null,scope_key text not null,domain text not null,subject_key text not null,pattern_key text not null,outcome_direction text not null check(outcome_direction in('positive','negative','neutral','conditional')),statement text not null,statement_hash text not null,expected_outcome jsonb not null,scope jsonb not null,evidence_window_start timestamptz,evidence_window_end timestamptz,confidence numeric not null default 0 check(confidence between 0 and 1),confidence_band text not null default 'low',status text not null default 'hypothesis' check(status in('hypothesis','accumulating','needs_review','validated','approved','rejected','archived')),created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),unique(business_id,identity_key,statement_hash)
);
create table if not exists public.learning_evidence_references (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),hypothesis_id uuid not null references public.learning_hypotheses(id),observation_id uuid not null references public.learning_observations(id),role text not null check(role in('supporting','contradicting','neutral','contextual')),rationale text not null,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),unique(hypothesis_id,observation_id,role)
);
create table if not exists public.learning_validation_runs (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),hypothesis_id uuid not null references public.learning_hypotheses(id),status text not null check(status in('validated','needs_review','failed')),confidence numeric not null check(confidence between 0 and 1),confidence_band text not null,validation_policy text not null,evidence_count int not null,independent_source_count int not null,campaign_count int not null,conflict boolean not null,diagnostics jsonb not null,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id)
);
create table if not exists public.learning_conflicts (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),identity_key text not null,hypothesis_ids uuid[] not null,kind text not null,status text not null default 'open' check(status in('open','resolved','archived')),resolution text,resolved_hypothesis_id uuid,resolved_at timestamptz,resolved_by uuid references auth.users(id),created_at timestamptz not null default now()
);
create unique index if not exists learning_conflicts_open_idx on public.learning_conflicts(business_id,identity_key) where status='open';
create table if not exists public.learning_versions (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),identity_key text not null,scope_key text not null,domain text not null,subject_key text not null,pattern_key text not null,outcome_direction text not null,conclusion jsonb not null,version int not null,status text not null check(status in('approved','weakened','expired','revoked','archived','retired')),confidence numeric not null check(confidence between 0 and 1),confidence_band text not null,scope jsonb not null,evidence_window_start timestamptz,evidence_window_end timestamptz,validation_policy text not null,decay_policy jsonb not null,valid_from timestamptz,valid_until timestamptz,supersedes uuid references public.learning_versions(id),approved_at timestamptz not null,approved_by uuid not null references auth.users(id),approval_reason text not null,created_at timestamptz not null default now(),unique(business_id,identity_key,scope_key,version)
);
create unique index if not exists learning_versions_single_successor_idx on public.learning_versions(supersedes) where supersedes is not null;
create table if not exists public.learning_version_evidence (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),version_id uuid not null references public.learning_versions(id),observation_id uuid not null references public.learning_observations(id),role text not null,created_at timestamptz not null default now(),unique(version_id,observation_id,role)
);
create table if not exists public.learning_decay_assessments (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),version_id uuid not null references public.learning_versions(id),assessed_at timestamptz not null,policy_version text not null,previous_confidence numeric not null,decayed_confidence numeric not null,eligible boolean not null,next_review_at timestamptz,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),unique(version_id,assessed_at,policy_version)
);
create table if not exists public.learning_candidate_updates (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),proposed_domain text not null,proposed_identity_key text not null,proposed_value jsonb not null,source_kind text not null,source_reference_id text not null,evidence jsonb not null default '[]',status text not null default 'candidate' check(status in('candidate','under_review','accepted_for_validation','rejected')),created_at timestamptz not null default now(),created_by uuid not null references auth.users(id)
);
create table if not exists public.learning_audit_events (
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id),actor_id uuid,action text not null,target_kind text not null,target_id text not null,correlation_id text,reason text,metadata jsonb not null default '{}',created_at timestamptz not null default now()
);

create or replace function public.reject_learning_immutable_mutation() returns trigger language plpgsql as $$ begin raise exception '% is append-only',tg_table_name; end $$;
do $$ declare t text; begin foreach t in array array['learning_observations','learning_evidence_references','learning_validation_runs','learning_versions','learning_version_evidence','learning_decay_assessments','learning_audit_events'] loop execute format('drop trigger if exists %I on public.%I',t||'_append_only',t); execute format('create trigger %I before update or delete on public.%I for each row execute function public.reject_learning_immutable_mutation()',t||'_append_only',t); end loop; end $$;

create or replace function public.register_learning_observation(p_business_id uuid,p_source_kind text,p_source_reference_id text,p_campaign_id uuid,p_experiment_id text,p_metric text,p_value jsonb,p_unit text,p_sample_basis jsonb,p_scope jsonb,p_observed_at timestamptz,p_collection_window jsonb,p_attribution_method text,p_reliability numeric,p_provenance_hash text,p_metadata jsonb,p_actor_id uuid,p_correlation_id text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare o public.learning_observations; inserted boolean:=true; begin
 if auth.uid() is distinct from p_actor_id or not public.is_business_member(p_business_id) then raise exception 'business member identity required'; end if;
 insert into public.learning_observations(business_id,source_kind,source_reference_id,campaign_id,experiment_id,metric,value,unit,sample_basis,scope,observed_at,collection_window,attribution_method,reliability,provenance_hash,metadata,created_by) values(p_business_id,p_source_kind,p_source_reference_id,p_campaign_id,p_experiment_id,p_metric,p_value,p_unit,p_sample_basis,p_scope,p_observed_at,p_collection_window,p_attribution_method,p_reliability,p_provenance_hash,p_metadata,p_actor_id) on conflict(business_id,source_kind,source_reference_id,provenance_hash) do nothing returning * into o;
 if o.id is null then inserted:=false; select * into o from public.learning_observations where business_id=p_business_id and source_kind=p_source_kind and source_reference_id=p_source_reference_id and provenance_hash=p_provenance_hash; end if;
 insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id) values(p_business_id,p_actor_id,case when inserted then 'learning_observation_registered' else 'learning_observation_duplicate' end,'learning_observation',o.id::text,p_correlation_id); return to_jsonb(o)||jsonb_build_object('duplicate',not inserted); end $$;

create or replace function public.register_learning_hypothesis(p_business_id uuid,p_identity_key text,p_scope_key text,p_domain text,p_subject_key text,p_pattern_key text,p_outcome_direction text,p_statement text,p_statement_hash text,p_expected_outcome jsonb,p_scope jsonb,p_evidence_window_start timestamptz,p_evidence_window_end timestamptz,p_observation_ids uuid[],p_actor_id uuid,p_correlation_id text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare h public.learning_hypotheses; observation_id uuid; begin
 if auth.uid() is distinct from p_actor_id or not public.is_business_member(p_business_id) then raise exception 'business member identity required'; end if;
 if cardinality(p_observation_ids)=0 or exists(select 1 from unnest(p_observation_ids) x where not exists(select 1 from public.learning_observations o where o.id=x and o.business_id=p_business_id)) then raise exception 'owned observation evidence required'; end if;
 insert into public.learning_hypotheses(business_id,identity_key,scope_key,domain,subject_key,pattern_key,outcome_direction,statement,statement_hash,expected_outcome,scope,evidence_window_start,evidence_window_end,created_by) values(p_business_id,p_identity_key,p_scope_key,p_domain,p_subject_key,p_pattern_key,p_outcome_direction,p_statement,p_statement_hash,p_expected_outcome,p_scope,p_evidence_window_start,p_evidence_window_end,p_actor_id) on conflict(business_id,identity_key,statement_hash) do update set id=learning_hypotheses.id returning * into h;
 foreach observation_id in array p_observation_ids loop insert into public.learning_evidence_references(business_id,hypothesis_id,observation_id,role,rationale,created_by) values(p_business_id,h.id,observation_id,'supporting','initial hypothesis evidence',p_actor_id) on conflict do nothing; end loop;
 insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id) values(p_business_id,p_actor_id,'learning_hypothesis_registered','learning_hypothesis',h.id::text,p_correlation_id); return to_jsonb(h); end $$;

create or replace function public.attach_learning_evidence(p_business_id uuid,p_hypothesis_id uuid,p_observation_id uuid,p_role text,p_rationale text,p_actor_id uuid,p_correlation_id text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare e public.learning_evidence_references; begin
 if auth.uid() is distinct from p_actor_id or not public.is_business_member(p_business_id) then raise exception 'business member identity required'; end if;
 if not exists(select 1 from public.learning_hypotheses where id=p_hypothesis_id and business_id=p_business_id) or not exists(select 1 from public.learning_observations where id=p_observation_id and business_id=p_business_id) then raise exception 'owned hypothesis and observation required'; end if;
 insert into public.learning_evidence_references(business_id,hypothesis_id,observation_id,role,rationale,created_by) values(p_business_id,p_hypothesis_id,p_observation_id,p_role,p_rationale,p_actor_id) on conflict(hypothesis_id,observation_id,role) do update set id=learning_evidence_references.id returning * into e; update public.learning_hypotheses set status='accumulating' where id=p_hypothesis_id and status='hypothesis'; insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id) values(p_business_id,p_actor_id,'learning_evidence_attached','learning_hypothesis',p_hypothesis_id::text,p_correlation_id); return to_jsonb(e); end $$;

create or replace function public.save_learning_validation(p_business_id uuid,p_hypothesis_id uuid,p_status text,p_confidence numeric,p_confidence_band text,p_validation_policy text,p_evidence_count int,p_independent_source_count int,p_campaign_count int,p_conflict boolean,p_diagnostics jsonb,p_actor_id uuid,p_correlation_id text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare r public.learning_validation_runs; h public.learning_hypotheses; ids uuid[]; begin
 if auth.uid() is distinct from p_actor_id or not public.is_business_member(p_business_id) then raise exception 'business member identity required'; end if;
 update public.learning_hypotheses set status=p_status,confidence=p_confidence,confidence_band=p_confidence_band where id=p_hypothesis_id and business_id=p_business_id and status in('hypothesis','accumulating','needs_review','validated') returning * into h; if h.id is null then raise exception 'validatable hypothesis not found'; end if;
 insert into public.learning_validation_runs(business_id,hypothesis_id,status,confidence,confidence_band,validation_policy,evidence_count,independent_source_count,campaign_count,conflict,diagnostics,created_by) values(p_business_id,p_hypothesis_id,p_status,p_confidence,p_confidence_band,p_validation_policy,p_evidence_count,p_independent_source_count,p_campaign_count,p_conflict,p_diagnostics,p_actor_id) returning * into r;
 if p_conflict then select array_agg(id) into ids from public.learning_hypotheses where business_id=p_business_id and identity_key=h.identity_key and status in('needs_review','validated'); insert into public.learning_conflicts(business_id,identity_key,hypothesis_ids,kind) values(p_business_id,h.identity_key,coalesce(ids,array[p_hypothesis_id]),'evidence_conflict') on conflict(business_id,identity_key) where status='open' do update set hypothesis_ids=excluded.hypothesis_ids; end if;
 insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id,metadata) values(p_business_id,p_actor_id,'learning_validation_completed','learning_validation_run',r.id::text,p_correlation_id,p_diagnostics); return to_jsonb(r); end $$;

create or replace function public.approve_learning_hypothesis(p_business_id uuid,p_hypothesis_id uuid,p_conclusion jsonb,p_actor_id uuid,p_reason text,p_valid_from timestamptz,p_valid_until timestamptz,p_decay_policy jsonb,p_correlation_id text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare h public.learning_hypotheses; current_v public.learning_versions; v public.learning_versions; begin
 if not public.can_review_business_knowledge(p_business_id,p_actor_id,true) then raise exception 'authorized human reviewer required'; end if; if length(btrim(coalesce(p_reason,'')))=0 then raise exception 'approval reason required'; end if;
 select * into h from public.learning_hypotheses where id=p_hypothesis_id and business_id=p_business_id and status='validated' for update; if h.id is null then raise exception 'validated hypothesis required'; end if;
 if exists(select 1 from public.learning_conflicts where business_id=p_business_id and identity_key=h.identity_key and status='open') then raise exception 'open learning conflict blocks approval'; end if;
 select x.* into current_v from public.learning_versions x where x.business_id=p_business_id and x.identity_key=h.identity_key and x.scope_key=h.scope_key and not exists(select 1 from public.learning_versions s where s.supersedes=x.id) order by x.version desc limit 1 for update;
 insert into public.learning_versions(business_id,identity_key,scope_key,domain,subject_key,pattern_key,outcome_direction,conclusion,version,status,confidence,confidence_band,scope,evidence_window_start,evidence_window_end,validation_policy,decay_policy,valid_from,valid_until,supersedes,approved_at,approved_by,approval_reason) values(p_business_id,h.identity_key,h.scope_key,h.domain,h.subject_key,h.pattern_key,h.outcome_direction,p_conclusion,coalesce(current_v.version,0)+1,'approved',h.confidence,h.confidence_band,h.scope,h.evidence_window_start,h.evidence_window_end,'learning-validation-v1',p_decay_policy,p_valid_from,p_valid_until,current_v.id,now(),p_actor_id,p_reason) returning * into v;
 insert into public.learning_version_evidence(business_id,version_id,observation_id,role) select business_id,v.id,observation_id,role from public.learning_evidence_references where hypothesis_id=h.id; update public.learning_hypotheses set status='approved' where id=h.id;
 insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id,reason) values(p_business_id,p_actor_id,'learning_hypothesis_approved','learning_version',v.id::text,p_correlation_id,p_reason); return to_jsonb(v); end $$;

create or replace function public.reject_learning_hypothesis(p_business_id uuid,p_hypothesis_id uuid,p_actor_id uuid,p_reason text,p_correlation_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare h public.learning_hypotheses; begin if not public.can_review_business_knowledge(p_business_id,p_actor_id,true) then raise exception 'authorized human reviewer required'; end if; update public.learning_hypotheses set status='rejected' where id=p_hypothesis_id and business_id=p_business_id and status<>'approved' returning * into h; if h.id is null then raise exception 'rejectable hypothesis not found'; end if; insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id,reason) values(p_business_id,p_actor_id,'learning_hypothesis_rejected','learning_hypothesis',h.id::text,p_correlation_id,p_reason); return to_jsonb(h); end $$;

create or replace function public.resolve_learning_conflict(p_business_id uuid,p_conflict_id uuid,p_selected_hypothesis_id uuid,p_actor_id uuid,p_reason text,p_correlation_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare c public.learning_conflicts; begin if not public.can_review_business_knowledge(p_business_id,p_actor_id,true) then raise exception 'authorized human reviewer required'; end if; select * into c from public.learning_conflicts where id=p_conflict_id and business_id=p_business_id and status='open' for update; if c.id is null or not(p_selected_hypothesis_id=any(c.hypothesis_ids)) then raise exception 'valid conflict selection required'; end if; update public.learning_hypotheses set status=case when id=p_selected_hypothesis_id then 'validated' else 'rejected' end where business_id=p_business_id and id=any(c.hypothesis_ids); update public.learning_conflicts set status='resolved',resolution=p_reason,resolved_hypothesis_id=p_selected_hypothesis_id,resolved_at=now(),resolved_by=p_actor_id where id=c.id returning * into c; insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id,reason) values(p_business_id,p_actor_id,'learning_conflict_resolved','learning_conflict',c.id::text,p_correlation_id,p_reason); return to_jsonb(c); end $$;

create or replace function public.assess_learning_decay(p_business_id uuid,p_as_of timestamptz,p_policy_version text,p_actor_id uuid,p_correlation_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v public.learning_versions; a public.learning_decay_assessments; results jsonb:='[]'; half_life numeric; days_old numeric; score numeric; minimum numeric; begin if auth.uid() is distinct from p_actor_id or not public.is_business_member(p_business_id) then raise exception 'business member identity required'; end if; for v in select x.* from public.learning_versions x where x.business_id=p_business_id and x.status='approved' and not exists(select 1 from public.learning_versions s where s.supersedes=x.id) loop half_life:=greatest(1,coalesce((v.decay_policy->>'halfLifeDays')::numeric,90)); minimum:=coalesce((v.decay_policy->>'minimumConfidence')::numeric,.5); days_old:=greatest(0,extract(epoch from(p_as_of-coalesce(v.evidence_window_end,v.approved_at)))/86400); score:=round((v.confidence*power(.5,days_old/half_life))::numeric,4); insert into public.learning_decay_assessments(business_id,version_id,assessed_at,policy_version,previous_confidence,decayed_confidence,eligible,next_review_at,created_by) values(p_business_id,v.id,p_as_of,p_policy_version,v.confidence,score,score>=minimum,p_as_of+make_interval(days=>ceil(half_life/4)::int),p_actor_id) on conflict(version_id,assessed_at,policy_version) do update set id=learning_decay_assessments.id returning * into a; results:=results||to_jsonb(a); end loop; insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id,metadata) values(p_business_id,p_actor_id,'learning_decay_assessed','learning_memory',p_business_id::text,p_correlation_id,jsonb_build_object('asOf',p_as_of)); return results; end $$;

create or replace function public.transition_learning_version(p_business_id uuid,p_version_id uuid,p_status text,p_actor_id uuid,p_reason text,p_correlation_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare current_v public.learning_versions; v public.learning_versions; begin if p_status not in('revoked','expired','archived','retired') then raise exception 'invalid transition'; end if; if not public.can_review_business_knowledge(p_business_id,p_actor_id,true) then raise exception 'authorized human reviewer required'; end if; select * into current_v from public.learning_versions where id=p_version_id and business_id=p_business_id for update; if current_v.id is null or exists(select 1 from public.learning_versions where supersedes=current_v.id) then raise exception 'current version required'; end if; insert into public.learning_versions(business_id,identity_key,scope_key,domain,subject_key,pattern_key,outcome_direction,conclusion,version,status,confidence,confidence_band,scope,evidence_window_start,evidence_window_end,validation_policy,decay_policy,valid_from,valid_until,supersedes,approved_at,approved_by,approval_reason) values(p_business_id,current_v.identity_key,current_v.scope_key,current_v.domain,current_v.subject_key,current_v.pattern_key,current_v.outcome_direction,current_v.conclusion,current_v.version+1,p_status,current_v.confidence,current_v.confidence_band,current_v.scope,current_v.evidence_window_start,current_v.evidence_window_end,current_v.validation_policy,current_v.decay_policy,current_v.valid_from,current_v.valid_until,current_v.id,now(),p_actor_id,p_reason) returning * into v; insert into public.learning_version_evidence(business_id,version_id,observation_id,role) select business_id,v.id,observation_id,role from public.learning_version_evidence where version_id=current_v.id; insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id,reason) values(p_business_id,p_actor_id,'learning_version_'||p_status,'learning_version',v.id::text,p_correlation_id,p_reason); return to_jsonb(v); end $$;

create or replace function public.create_learning_candidate_update(p_business_id uuid,p_proposed_domain text,p_proposed_identity_key text,p_proposed_value jsonb,p_source_kind text,p_source_reference_id text,p_evidence jsonb,p_actor_id uuid,p_correlation_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare u public.learning_candidate_updates; begin if auth.uid() is distinct from p_actor_id or not public.is_business_member(p_business_id) then raise exception 'business member identity required'; end if; insert into public.learning_candidate_updates(business_id,proposed_domain,proposed_identity_key,proposed_value,source_kind,source_reference_id,evidence,created_by) values(p_business_id,p_proposed_domain,p_proposed_identity_key,p_proposed_value,p_source_kind,p_source_reference_id,p_evidence,p_actor_id) returning * into u; insert into public.learning_audit_events(business_id,actor_id,action,target_kind,target_id,correlation_id) values(p_business_id,p_actor_id,'learning_candidate_update_created','learning_candidate_update',u.id::text,p_correlation_id); return to_jsonb(u); end $$;

do $$ declare t text; begin foreach t in array array['learning_observations','learning_hypotheses','learning_evidence_references','learning_validation_runs','learning_conflicts','learning_versions','learning_version_evidence','learning_decay_assessments','learning_candidate_updates','learning_audit_events'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists %I on public.%I',t||'_member_select',t); execute format('create policy %I on public.%I for select to authenticated using (public.is_business_member(business_id))',t||'_member_select',t); execute format('revoke insert,update,delete on public.%I from authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end $$;
do $$ declare signature text; begin foreach signature in array array['register_learning_observation(uuid,text,text,uuid,text,text,jsonb,text,jsonb,jsonb,timestamptz,jsonb,text,numeric,text,jsonb,uuid,text)','register_learning_hypothesis(uuid,text,text,text,text,text,text,text,text,jsonb,jsonb,timestamptz,timestamptz,uuid[],uuid,text)','attach_learning_evidence(uuid,uuid,uuid,text,text,uuid,text)','save_learning_validation(uuid,uuid,text,numeric,text,text,integer,integer,integer,boolean,jsonb,uuid,text)','approve_learning_hypothesis(uuid,uuid,jsonb,uuid,text,timestamptz,timestamptz,jsonb,text)','reject_learning_hypothesis(uuid,uuid,uuid,text,text)','resolve_learning_conflict(uuid,uuid,uuid,uuid,text,text)','assess_learning_decay(uuid,timestamptz,text,uuid,text)','transition_learning_version(uuid,uuid,text,uuid,text,text)','create_learning_candidate_update(uuid,text,text,jsonb,text,text,jsonb,uuid,text)'] loop execute format('revoke all on function public.%s from public',signature); execute format('grant execute on function public.%s to authenticated',signature); end loop; end $$;
create index if not exists learning_observations_campaign_idx on public.learning_observations(business_id,campaign_id,observed_at desc); create index if not exists learning_hypotheses_identity_idx on public.learning_hypotheses(business_id,identity_key,status); create index if not exists learning_versions_identity_idx on public.learning_versions(business_id,identity_key,scope_key,version desc); create index if not exists learning_decay_review_idx on public.learning_decay_assessments(business_id,next_review_at,eligible);
